import { Fixture, project } from './fixture';
import { endMill6, lWithHole, pocket, profile, shape } from './parts';

export default [
  {
    name: 'shape-path-data-absolute',
    covers:
      'path-data with absolute commands M L Q T C S A V Z, plus a second subpath with a rotated large-arc elliptical arc; outside profile and pocket',
    model: project({
      shapes: [
        shape('path', {
          type: 'path-data',
          pathCommands: [
            { id: 'c0', command: 'M', x: 0, y: 0 },
            { id: 'c1', command: 'L', x: 40, y: 0 },
            { id: 'c2', command: 'Q', x1: 55, y1: 0, x: 55, y: 15 },
            { id: 'c3', command: 'T', x: 60, y: 35 },
            {
              id: 'c4',
              command: 'C',
              x1: 60,
              y1: 50,
              x2: 45,
              y2: 55,
              x: 35,
              y: 50,
            },
            { id: 'c5', command: 'S', x2: 20, y2: 40, x: 10, y: 50 },
            {
              id: 'c6',
              command: 'A',
              rx: 12,
              ry: 12,
              rotation: 0,
              largeArc: false,
              sweep: false,
              x: 0,
              y: 30,
            },
            { id: 'c7', command: 'V', y: 0 },
            { id: 'c8', command: 'Z' },
            { id: 'c9', command: 'M', x: 80, y: 0 },
            { id: 'c10', command: 'H', x: 95 },
            {
              id: 'c11',
              command: 'A',
              rx: 15,
              ry: 8,
              rotation: 30,
              largeArc: true,
              sweep: true,
              x: 110,
              y: 10,
            },
            { id: 'c12', command: 'Z' },
          ],
        }),
      ],
      tools: [endMill6],
      operations: [profile('op-profile', 'path'), pocket('op-pocket', 'path')],
    }),
  },
  {
    name: 'shape-path-data-relative',
    covers:
      'path-data with relative commands m l q t c s a v h (closed by Z), a second relative subpath after Z with a rotated large-arc elliptical arc (sweep off); outside profile and pocket',
    model: project({
      shapes: [
        shape('path', {
          type: 'path-data',
          pathCommands: [
            { id: 'c0', command: 'm', x: 0, y: 0 },
            { id: 'c1', command: 'l', x: 30, y: 0 },
            { id: 'c2', command: 'q', x1: 15, y1: 0, x: 15, y: 15 },
            { id: 'c3', command: 't', x: 5, y: 20 },
            {
              id: 'c4',
              command: 'c',
              x1: 0,
              y1: 15,
              x2: -15,
              y2: 20,
              x: -25,
              y: 15,
            },
            { id: 'c5', command: 's', x2: -10, y2: -10, x: -20, y: 0 },
            {
              id: 'c6',
              command: 'a',
              rx: 12,
              ry: 12,
              rotation: 0,
              largeArc: false,
              sweep: false,
              x: -10,
              y: -20,
            },
            { id: 'c7', command: 'v', y: -20 },
            { id: 'c8', command: 'h', x: 5 },
            { id: 'c9', command: 'Z' },
            { id: 'c10', command: 'm', x: 70, y: 0 },
            { id: 'c11', command: 'h', x: 10 },
            {
              id: 'c12',
              command: 'a',
              rx: 15,
              ry: 8,
              rotation: -20,
              largeArc: true,
              sweep: false,
              x: 20,
              y: 10,
            },
            { id: 'c13', command: 'Z' },
          ],
        }),
      ],
      tools: [endMill6],
      operations: [profile('op-profile', 'path'), pocket('op-pocket', 'path')],
    }),
  },
  {
    name: 'shape-path-data-open',
    covers:
      'open path-data (no Z): absolute arc, relative large arc, cubic and line; on-line and outside profiles',
    model: project({
      shapes: [
        shape('path', {
          type: 'path-data',
          pathCommands: [
            { id: 'c0', command: 'M', x: 0, y: 0 },
            {
              id: 'c1',
              command: 'A',
              rx: 20,
              ry: 20,
              rotation: 0,
              largeArc: false,
              sweep: true,
              x: 40,
              y: 0,
            },
            {
              id: 'c2',
              command: 'a',
              rx: 10,
              ry: 10,
              rotation: 0,
              largeArc: true,
              sweep: false,
              x: 15,
              y: 5,
            },
            {
              id: 'c3',
              command: 'C',
              x1: 70,
              y1: 30,
              x2: 80,
              y2: -10,
              x: 90,
              y: 20,
            },
            { id: 'c4', command: 'L', x: 90, y: 40 },
          ],
        }),
      ],
      tools: [endMill6],
      operations: [
        profile('op-on-line', 'path', { side: 'on-line' }),
        profile('op-outside', 'path'),
      ],
    }),
  },
  {
    name: 'shape-path-data-holes',
    covers:
      'path-data with holes: an L outline with a square hole (concave corner), and a ring of two semicircular arcs with a reversed inner circle; profile (both, holes only) and pocket',
    model: project({
      shapes: [
        shape('l-hole', lWithHole),
        shape('ring', {
          type: 'path-data',
          pathCommands: [
            { id: 'c0', command: 'M', x: 70, y: 25 },
            {
              id: 'c1',
              command: 'A',
              rx: 20,
              ry: 20,
              rotation: 0,
              largeArc: false,
              sweep: true,
              x: 110,
              y: 25,
            },
            {
              id: 'c2',
              command: 'A',
              rx: 20,
              ry: 20,
              rotation: 0,
              largeArc: false,
              sweep: true,
              x: 70,
              y: 25,
            },
            { id: 'c3', command: 'Z' },
            { id: 'c4', command: 'M', x: 82, y: 25 },
            {
              id: 'c5',
              command: 'a',
              rx: 8,
              ry: 8,
              rotation: 0,
              largeArc: false,
              sweep: false,
              x: 16,
              y: 0,
            },
            {
              id: 'c6',
              command: 'a',
              rx: 8,
              ry: 8,
              rotation: 0,
              largeArc: false,
              sweep: false,
              x: -16,
              y: 0,
            },
            { id: 'c7', command: 'Z' },
          ],
        }),
      ],
      tools: [endMill6],
      operations: [
        profile('op-l-profile', 'l-hole'),
        pocket('op-l-pocket', 'l-hole'),
        profile('op-ring-profile', 'ring', { mode: 'holes', side: 'inside' }),
        pocket('op-ring-pocket', 'ring'),
      ],
    }),
  },
] satisfies Fixture[];
