// Bundles the regression harness (run.ts) for Node and runs it with the
// arguments given: node scripts/regression/build.mjs record <dir> …
//
// With `--src <dir>` first, the app's code comes from <dir>/src instead of
// this checkout's (e.g. a worktree of master, for the baseline): the harness
// stays this one.
import { build } from "esbuild";
import { spawnSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "../..");
const args = process.argv.slice(2);
let srcRoot = root;
if (args[0] === "--src") {
  srcRoot = path.resolve(args[1]);
  args.splice(0, 2);
}

// Every fixture file in projects/.
const files = fs
  .readdirSync(path.join(here, "projects"))
  .filter((f) => f.endsWith(".ts") && !["fixture.ts", "_all.ts"].includes(f))
  .sort();
fs.writeFileSync(
  path.join(here, "projects/_all.ts"),
  `// Generated by build.mjs: every fixture file here.\nimport { Fixture } from './fixture';\n` +
    files
      .map((f, i) => `import f${i} from './${f.replace(/\.ts$/, "")}';`)
      .join("\n") +
    `\n\nexport default [${files.map((_, i) => `...f${i}`).join(", ")}] as Fixture[];\n`,
);

const worker = path.join(srcRoot, "src/worker/index.ts");
await build({
  entryPoints: [path.join(here, "run.ts")],
  bundle: true,
  // Bare imports from the other tree resolve to this checkout's packages.
  nodePaths: [path.join(root, "node_modules")],
  platform: "node",
  format: "esm",
  target: "node22",
  outfile: path.join(here, ".build/run.mjs"),
  logLevel: "warning",
  sourcemap: "inline",
  banner: {
    js: [
      "import { createRequire as __createRequire } from 'module';",
      "import { fileURLToPath as __fileURLToPath } from 'url';",
      "import { dirname as __dirnameOf } from 'path';",
      "const require = __createRequire(import.meta.url);",
      "const __dirname = __dirnameOf(__fileURLToPath(import.meta.url));",
    ].join("\n"),
  },
  plugins: [
    {
      name: "harness",
      setup(b) {
        // The app's code from the other source tree.
        if (srcRoot !== root) {
          b.onResolve({ filter: /^\./ }, (a) => {
            const resolved = path.resolve(a.resolveDir, a.path);
            if (!resolved.startsWith(path.join(root, "src") + path.sep))
              return undefined;
            const other = path.join(srcRoot, path.relative(root, resolved));
            for (const candidate of [
              other,
              `${other}.ts`,
              path.join(other, "index.ts"),
            ]) {
              if (fs.existsSync(candidate) && fs.statSync(candidate).isFile()) {
                return candidate === path.join(srcRoot, "src/worker/index.ts")
                  ? { path: path.join(here, "fake-worker.ts") }
                  : { path: candidate };
              }
            }
            return undefined;
          });
        }
        // The worker pool → direct calls.
        b.onResolve({ filter: /worker$/ }, (args) => {
          const resolved = path.resolve(args.resolveDir, args.path);
          return resolved === worker.replace(/\/index\.ts$/, "") ||
            resolved === worker.replace(/\.ts$/, "")
            ? { path: path.join(here, "fake-worker.ts") }
            : undefined;
        });
        // Clipper's wasm from node_modules, not next to the page.
        b.onLoad({ filter: /src\/cam\/clipper\.ts$/ }, (args) => ({
          contents: fs
            .readFileSync(args.path, "utf8")
            .replace(
              /locateFile: \(\) => `clipper2z\.wasm\?v=\$\{clipperVersion\}`/,
              `locateFile: () => ${JSON.stringify(path.join(root, "node_modules/clipper2-wasm/dist/es/clipper2z.wasm"))}`,
            ),
          loader: "ts",
        }));
      },
    },
  ],
});

const result = spawnSync(
  process.execPath,
  ["--enable-source-maps", path.join(here, ".build/run.mjs"), ...args],
  { stdio: "inherit" },
);
process.exit(result.status ?? 1);
