// Builds the kernel to WebAssembly and puts it where the app loads it:
// dist/cnc-kernel.wasm (an asset, see angular.json) and its versioned URL in
// src/cam/kernel-wasm.ts. Both are committed, so building the app needs no
// Rust. Run after changing the Rust code: npm run kernel
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const cargo = fs.existsSync(path.join(os.homedir(), '.cargo/bin/cargo'))
  ? path.join(os.homedir(), '.cargo/bin/cargo')
  : 'cargo';
execFileSync(cargo, ['test', '--release', '--quiet'], { cwd: here, stdio: 'inherit' });
execFileSync(cargo, ['build', '--release', '--target', 'wasm32-unknown-unknown'], {
  cwd: here,
  stdio: 'inherit',
});
const wasm = fs.readFileSync(
  path.join(here, 'target/wasm32-unknown-unknown/release/cnc_kernel.wasm'),
);
fs.mkdirSync(path.join(here, 'dist'), { recursive: true });
fs.writeFileSync(path.join(here, 'dist/cnc-kernel.wasm'), wasm);
const hash = createHash('sha256').update(wasm).digest('hex').slice(0, 12);
fs.writeFileSync(
  path.join(here, '../src/cam/kernel-wasm.ts'),
  `// Generated by kernel/build.mjs: the kernel's WebAssembly, by content, so a\n// cached copy is never paired with other code.\nexport const KERNEL_WASM = 'cnc-kernel.wasm?v=${hash}';\n`,
);
console.log(`kernel: ${wasm.length} bytes, ${hash}`);
